--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 8.0.856
--   Created On : sábado, 29 agosto, 2015 
--   DBMS       : MySql 
--   -------------------------------------------------- 


SET FOREIGN_KEY_CHECKS=0;


--  Drop Tables, Stored Procedures and Views 

DROP TABLE IF EXISTS Goal
;
DROP TABLE IF EXISTS Level
;
DROP TABLE IF EXISTS Practice
;
DROP TABLE IF EXISTS ProcessArea
;
DROP TABLE IF EXISTS Project
;
DROP TABLE IF EXISTS Roles
;
DROP TABLE IF EXISTS Steps
;


--  Create Tables 
CREATE TABLE Goal
(
	k_id INTEGER NOT NULL,
	n_processArea INTEGER NOT NULL,
	t_name VARCHAR(50),
	t_description VARCHAR(50),
	t_type VARCHAR(50),
	PRIMARY KEY (k_id),
	KEY (n_processArea)
) 
;


CREATE TABLE Level
(
	k_id INTEGER NOT NULL,
	t_name VARCHAR(50),
	PRIMARY KEY (k_id)
) 
;


CREATE TABLE Practice
(
	k_id INTEGER NOT NULL,
	t_name VARCHAR(50),
	t_description VARCHAR(50),
	n_goal INTEGER,
	PRIMARY KEY (k_id),
	KEY (n_goal)
) 
;


CREATE TABLE ProcessArea
(
	k_id VARCHAR(50) NOT NULL,
	n_level INTEGER NOT NULL,
	t_name VARCHAR(50),
	t_description VARCHAR(50),
	PRIMARY KEY (k_id),
	KEY (n_level)
) 
;


CREATE TABLE Project
(
	k_id INTEGER NOT NULL,
	t_name VARCHAR(50),
	PRIMARY KEY (k_id)
) 
;


CREATE TABLE Roles
(
	k_idRol INT NOT NULL,
	t_roleName BIGINT NOT NULL,
	PRIMARY KEY (k_idRol)
) 
;


CREATE TABLE Steps
(
	k_idStep INT NOT NULL,
	t_description VARCHAR(50),
	n_practice INT,
	n_yestStep INT,
	n_noStep INT,
	t_typeStep VARBINARY(50) COMMENT 'Task, Decision, Process',
	n_rol INT,
	PRIMARY KEY (k_idStep),
	KEY (n_yestStep),
	KEY (n_noStep),
	KEY (n_practice),
	KEY (n_rol)
) 
;


SET FOREIGN_KEY_CHECKS=1;
